import mal_tools as mal
import database as db


mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/38009/Re_Stage_Dream_Days%E2%99%AA")

quit()

mal.downloadInsertAnimeCharacters("")


mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/11785/Haiyore_Nyaruko-san")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/27441/Show_By_Rock")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/32038/Show_By_Rock_")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/40763/Show_By_Rock_Mashumairesh")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/41520/Show_by_Rock_Stars")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/39681/D4DJ__First_Mix")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/39292/Princess_Connect_Re_Dive")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/13659/Ore_no_Imouto_ga_Konnani_Kawaii_Wake_ga_Nai")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/34798/Yuru_Camp%E2%96%B3")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/38474/Yuru_Camp%E2%96%B3_Season_2")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/32268/Koyomimonogatari")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/9253/Steins_Gate")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/19815/No_Game_No_Life")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/383/Galaxy_Angel")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/38992/Rikei_ga_Koi_ni_Ochita_no_de_Shoumei_shitemita")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/1887/Lucky%E2%98%86Star")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/2167/Clannad")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/4181/Clannad__After_Story")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/14741/Chuunibyou_demo_Koi_ga_Shitai")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/18671/Chuunibyou_demo_Koi_ga_Shitai_Ren")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/11751/Senki_Zesshou_Symphogear")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/15793/Senki_Zesshou_Symphogear_G")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/21573/Senki_Zesshou_Symphogear_GX")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/32836/Senki_Zesshou_Symphogear_AXZ")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/32843/Senki_Zesshou_Symphogear_XV")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/21273/Gochuumon_wa_Usagi_Desu_ka")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/29787/Gochuumon_wa_Usagi_Desu_ka")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/35249/Uma_Musume__Pretty_Derby_TV")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/37916/Uma_Musume__Pretty_Derby_-_BNW_no_Chikai")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/42941/Uma_Musume__Pretty_Derby_TV_Season_2")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/16157/Choujigen_Game_Neptune_The_Animation")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/15051/Love_Live_School_Idol_Project")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/32526/Love_Live_Sunshine")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/40879/Love_Live_Nijigasaki_Gakuen_School_Idol_Doukoukai")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/41169/Love_Live_Superstar")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/30547/Touhou_Niji_Sousaku_Doujin_Anime__Musou_Kakyou_Special")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/9874/Touhou_Niji_Sousaku_Doujin_Anime__Musou_Kakyou")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/36686/Hifuu_Katsudou_Kiroku__The_Sealed_Esoteric_History")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/32901/Eromanga-sensei")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/8769/Ore_no_Imouto_ga_Konnani_Kawaii_Wake_ga_Nai")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/6547/Angel_Beats")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/28999/Charlotte")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/16706/Kami_nomi_zo_Shiru_Sekai__Megami-hen")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/21085/Witch_Craft_Works")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/13759/Sakura-sou_no_Pet_na_Kanojo")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/27775/Plastic_Memories")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/8525/Kami_nomi_zo_Shiru_Sekai")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/10080/Kami_nomi_zo_Shiru_Sekai_II")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/15117/Kami_nomi_zo_Shiru_Sekai__Tenri-hen")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/31240/Re_Zero_kara_Hajimeru_Isekai_Seikatsu")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/42203/Re_Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season_Part_2")
mal.downloadInsertAnimeCharacters("https://myanimelist.net/anime/39587/Re_Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season")

db.createDatabase()

db.insertCharacter(mal.downloadCharacter(13468))
db.insertCharacter(mal.downloadCharacter(14015))
db.insertCharacter(mal.downloadCharacter(18866))
db.insertCharacter(mal.downloadCharacter(22306))
db.insertCharacter(mal.downloadCharacter(15636))
db.insertCharacter(mal.downloadCharacter(15449))
db.insertCharacter(mal.downloadCharacter(22322))
db.insertCharacter(mal.downloadCharacter(26275))
db.insertCharacter(mal.downloadCharacter(61371))
db.insertCharacter(mal.downloadCharacter(64167))
db.insertCharacter(mal.downloadCharacter(64173))
db.insertCharacter(mal.downloadCharacter(64169))
db.insertCharacter(mal.downloadCharacter(64165))
db.insertCharacter(mal.downloadCharacter(22037))
db.insertCharacter(mal.downloadCharacter(109213), "trash")
db.insertCharacter(mal.downloadCharacter(8128))
db.insertCharacter(mal.downloadCharacter(25170))
db.insertCharacter(mal.downloadCharacter(16192))
db.insertCharacter(mal.downloadCharacter(25171))
db.insertCharacter(mal.downloadCharacter(16193))
db.insertCharacter(mal.downloadCharacter(25169))
db.insertCharacter(mal.downloadCharacter(16194))
db.insertCharacter(mal.downloadCharacter(38940), "nae nae")
db.insertCharacter(mal.downloadCharacter(110137))
