from bs4 import BeautifulSoup

message = "現在、ゲーム内において、下記の不具合が発生しております。<br><br>■現在確認している不具合<br>【3/11 16:05追記】<br><div class=\"postscript-01\">・マチカネタンホイザの育成において、菊花賞に出走した後に発生する育成ウマ娘イベントのシナリオが、意図した内容にならない場合がある。<br>※「Make a new track!!～クライマックス開幕～」では該当のイベントは発生しません。</div><br>【3/10 18:52追記】<br><div class=\"postscript-01\">・「新設！URAファイナルズ」「アオハル杯～輝け、チームの絆～」における、サトノダイヤモンドの育成で、クラシック級宝塚記念に出走するウマ娘が意図しない内容になっている。</div><br>【3/10 11:15追記】<br><div class=\"postscript-01\">・「Make a new track!!～クライマックス開幕～」において、ライバルが出走するレースの勝敗演出で一部ウマ娘が意図した表示と異なる場合がある。<br>※本不具合は表示上のみの不具合です。</div><br>【3/9 18:55追記】<br><div class=\"postscript-01\">・アグネスタキオンの育成ウマ娘イベント「現【うつつ】の三冠ウマ娘」において、一部衣装の表示が崩れる場合がある。</div><br>【3/9 16:15追記】<br><div class=\"postscript-01\">・[一等星を目指して]アドマイヤベガのサポートカードイベント「進み続ける一等星」において、ウマ娘の表示が崩れる場合がある。</div><br>【3/8 20:15追記】<br><div class=\"postscript-01\">・育成にて、特定の手順を行うとトレーニング選択中ではないにもかかわらず、体力が減少する予測が表示される場合がある。<br>※本不具合は表示上のみの不具合です。</div><br>【3/8 15:02追記】<br><div class=\"postscript-01\">・サトノダイヤモンドの育成ウマ娘イベント「ジャパンCの後に・挑戦」にて、一部テキストが意図しない内容になっている。<br>※本不具合は表示上のみの不具合です。</div><br>【3/8 11:33追記】<br><div class=\"postscript-01\">・プレゼントにて、「カテゴリー」内の項目で絞り込みを行った際に、ルーレットコインが表示されない。<br>※表示されない場合は、絞り込みをOFFにすると表示されます。<br>・「winning the soul」「NEXT FRONTIER」のライブにて、一部ウマ娘の歌唱が意図しない設定になっている。</div><br>【3/7 19:15追記】<br><div class=\"postscript-01\">・ミホノブルボンの育成ウマ娘イベント「オペレーション/ダンスフィーバー」において、一部ウマ娘の表示が崩れる場合がある。</div><br>【3/7 18:37追記】<br><div class=\"postscript-01\">・任意のウマ娘を才能開花させた後に特定の操作を行った際、「覚醒Lv強化」画面でスキルを選択しても「スキル詳細」が表示されない場合がある。</div><br>【3/7 14:33追記】<br><div class=\"postscript-01\">・サイレンススズカの衣装を「ニュースターズ・ロゼ[A]」または「ニュースターズ・ロゼ[B]」に設定した際、腕の表示が崩れる場合がある。<br>・ルームマッチでトレーナーズカップを開催しようとした際、特定の操作を行うと開催コースが切り替わらなくなる。<br>※本不具合は、絞り込み項目の一覧が表示された画面に戻ることで解消されます。</div><br>【3/3 10:51追記】<br><div class=\"postscript-01\">・一部の端末において、ガチャ画面からストーリー画面に移動した際に、アプリが強制終了する場合がある。</div><br>【3/2 16:40追記】<br><div class=\"postscript-01\">・「覚醒Lv強化」の「アイテム入手」から各種蹄鉄交換画面へ移動した際に、意図していない種類の蹄鉄交換タブが選択されている場合がある。<br>※蹄鉄交換のラインナップは正常に表示されております。<br>※交換時に獲得できるアイテムや消費する蹄鉄の種類は、表示されているものと一致しております。</div><br><div dir=\"auto\">【2/28 19:05追記】</div><div class=\"postscript-01\">・一部の端末において、目覚まし時計を1000個以上所持している状態で「Make a new track!!～クライマックス開幕～」の育成中にコンティニュー画面を開くと、所持数が3桁目までしか表示されない。<br>※本不具合は表示上のみの不具合です。</div><br><div dir=\"auto\">【2/28 19:00追記】</div><div class=\"postscript-01\">・ストーリーイベント「羽ばたきのRun-up！」にて、一部の端末でイラストのウマ娘が想定より見切れてしまう場合がある。<br>・キタサンブラックのウマ娘ストーリー第4話において、一部ウマ娘の表示が崩れる場合がある。<br>・マチカネタンホイザの育成ウマ娘イベント「宝塚記念にむけて」「天皇賞（春）の後に・敗北後と次の夢」において、メジロマックイーンの衣装が意図した表示と異なっている。<br>・ビワハヤヒデのウマ娘ストーリー第4話において、右手に手帳の表示が残ってしまう場合がある。</div><br><div data-qa=\"block-kit-renderer\"><div dir=\"auto\">【2/28 18:29追記】</div><div class=\"postscript-01\">・「Make a new track!!～クライマックス開幕～」のメインシナリオイベント「古書とコーヒーの縁」において、サウンドをオフにしていても風の音が再生される。</div></div><br>【2/28 18:20追記】<br><div class=\"postscript-01\">・特定の背景を使用しているストーリーにおいて、ウマ娘の色合いが意図したものと異なっている。</div><br>【2/28 18:05追記】<br><div class=\"postscript-01\">・マチカネタンホイザの育成ウマ娘イベント「転んで、返って、待ちかねて」において、目標までの残りターン数の表示が意図した内容と異なる場合がある。<br>※本不具合は表示上のみの不具合です。<br>・アグネスタキオンの育成において、育成ウマ娘イベント「現【うつつ】の三冠ウマ娘」が意図しないタイミングで発生している。</div><br>【2/28 11:50追記】<br><div class=\"postscript-01\">・スキル獲得画面で特定の手順を行うと、獲得済みのスキル「良バ場◎」が複数表示される場合がある。<br>※本不具合は表示上のみの不具合です。</div><br>【2/24 19:38追記】<br><div class=\"postscript-01\">・「Make a new track!!～クライマックス開幕～」において、2つ以上の育成グッズを使用し、トレーニング選択直後に画面左上の効果アイコンを開くと進行不能になる場合がある。<br>※本現象は、アプリを再起動を行っていただくことで、解消されます。</div><br>【2/24 12:00追記】<br><div class=\"postscript-01\">・特定の手順で育成開始時に背景が拡大されて表示される場合がある。<br>※本不具合は表示上のみの不具合です。<br>・特定の手順で育成イベント中に「保存して中断」「あきらめる」が行える場合がある。<br>・特定の手順でシナリオレコード詳細の報酬タブで表示される「NEXT」の表示が画面外に表示される場合がある。<br>※本不具合は表示上のみの不具合です。<br>・「3Dレース表現の高品質化」をONの状態で、チーム競技場、チャンピオンズミーティングをプレイした場合、ゲートイン時の演出にて芝と影が正常に表示されない。<br>・「3Dレース表現の高品質化」をONにした際、レースにおいて、影が正常に表示されない場合がある。<br>・「Make a new track!!～クライマックス開幕～」において、育成ウマ娘がコンディション「片頭痛」の場合でも、やる気を上げる育成グッズが使用できてしまう。<br>・「Make a new track!!～クライマックス開幕～」において、特定の手順で育成グッズ「チアメガホン」「スパルタメガホン」「ブートキャンプメガホン」の使用中アイコンが非表示になる場合がある。<br>※本不具合は表示上のみの不具合です。<br>・「Make a new track!!～クライマックス開幕～」において、ライバルが出走する演出中に育成グッズのアイコンが表示される場合がある。<br>※本不具合は表示上のみの不具合です。<br>・「Make a new track!!～クライマックス開幕～」において、トゥインクルスタークライマックスの結果画面で意図しない優先度で順位が表示される場合がある。<br>※本不具合は表示上のみの不具合です。<br>・「Make a new track!!～クライマックス開幕～」において、コンティニューの残り回数がない状態で1着になり、[コンティニュー]を選択した際に、想定と異なる文言が表示される。<br>※本不具合は表示上のみの不具合です。<br>・「Make a new track!!～クライマックス開幕～」において、「育成ウマ娘選択」から表示する「ジュニア級メイクデビュー」のレース詳細表示が想定と異なっている。<br>※本不具合は表示上のみの不具合です。レースで獲得できる内容に影響はございません。<br>・「Make a new track!!～クライマックス開幕～」において、12月後半ターンに成績Ptが育成目標に到達していない場合、コンティニュー画面で「コンティニューをしなくても育成終了にはなりません」と表示される。<br>※本不具合は表示上のみの不具合で、[コンティニュー]を選択しない場合は育成が終了します。</div><br>【2/17 16:10追記】<br><div class=\"postscript-01\">・才能開花において、特定のタイミングで演出をスキップするとフリーズが発生し、進行不能になる場合がある。<br>※本現象は、アプリを再起動することで解消されます。</div><br>【2/15 10:34追記】<br><div class=\"postscript-01\">・メジロアルダンの育成において、「主な優勝歴」の表示優先度が意図しない内容になっている。<br>・メジロアルダンの育成において、クラシック三冠を達成後、レースに出走した際、ゲートイン時の実況内容が意図しない内容になっている。</div><br>【2/7 18:20追記】<br><div class=\"postscript-01\">・ストーリーイベントにおいて、イベントミッションからイベントPtを獲得して、ポイント到達報酬を制覇した場合、「到達報酬制覇」が表示されない。</div><br>【2/7 16:57追記】<br><div class=\"postscript-01\">・一部ウマ娘のウマ娘ストーリーにおいて、場面が切り替わる際に意図しないSEが再生される場合がある。</div><br>【1/31 17:30追記】<br><div class=\"postscript-01\">・サポートカード上限解放画面において、特定の絞り込みを行ったうえでサポートカードを選択後、結晶片交換画面に移動し[戻る]を選択した際、意図していないサポートカードが選択されている場合がある。<br>・才能開花画面において、特定の絞り込みを行ったうえで育成ウマ娘を選択後、女神像交換画面に移動し[戻る]を選択した際、意図していない育成ウマ娘が選択されている場合がある。</div><br>【12/17 15:52追記】<br><div class=\"postscript-01\">・イベント「トレーナー技能試験」開催中、ホーム画面にて、イベント開催中のボイスが再生されない。</div><br>【11/19 18:40追記】<br><div class=\"postscript-01\">・育成開始時のフレンドサポート選択で、同じトレーナーのサポートカードが2つ表示されることがある。&nbsp;</div><div class=\"postscript-01\">・オプションの「サウンド」で「実況・解説」をオフにすると、実況や解説の文字送りが通常よりも速くなる。</div><br>【11/9 18:15追記】<br><div class=\"postscript-01\">・トーセンジョーダンの育成ウマ娘イベント「皐月賞にむけて」において、腕の表示が崩れる場合がある。</div><br>【8/30 12:08 追記】<br><div class=\"postscript-01\">・「アオハル杯～輝け、チームの絆～」の一部のイベントにて、特定のウマ娘の衣装が出走時の衣装と異なる場合がある。</div><br>【8/20 16:20追記】<br><div class=\"postscript-01\">・スマートファルコンの腕の表示が崩れる場合がある。</div><br>【2/25 19:45追記】<div class=\"postscript-01\">・一部の端末においてタイトル画面で強制終了する場合がある。<br>※端末を再起動することで解消する場合がございます。</div><br>【2/24 10:40掲載】<div class=\"postscript-01\"><div data-hasbody=\"true\" data-macro-name=\"panel\">・「メインストーリー」や「ウマ娘ストーリー」を縦画面で再生している際に、セリフのスクロールを行うと意図しない表示になる場合がある。</div></div><div class=\"postscript-01\"><div data-hasbody=\"true\" data-macro-name=\"panel\">・iOS端末で文字を入力する際にキーボードが閉じない場合がある。</div></div><br><br>■修正済みの不具合<br>【3/10 11:40追記】<br><div class=\"postscript-01\">・特定の条件において、一部育成ウマ娘のパドック内での演出が意図した内容と異なる。<br>※本不具合は表示上のみの不具合であり、3/7に修正されております。</div><br>【3/7 14:55追記】<br><div class=\"postscript-01\">・ビワハヤヒデの育成イベント「彼女の新たな側面」において、イベント冒頭でテキストボックスが表示されない場合がある。<br>・アドマイヤベガの育成ウマ娘イベント「ホープフルSの後に・大三角は描かれる」において、テイエムオペラオーの衣装が意図した表示と異なっている。<br>・「アオハル杯～輝け、チームの絆～」において、アオハル杯のレースに出走する相手チームのマチカネタンホイザの衣装が意図した表示と異なっている。<br>・「Make a new track!!～クライマックス開幕～」にて獲得できる二つ名「レジェンドウマ娘」の説明に誤字がある。<br>・レースにおいて、メジロアルダンのキャラ名を読み上げる男性実況の音声が聞き取りづらいことがある。<br>・メジロアルダンの育成ウマ娘イベント「温泉旅行」において、一部の効果音にノイズが入っている。<br>・アドマイヤベガのサポートカードイベント「不器用なトライアングラム」にて、選択肢の表記が意図した表記と異なっている。<br>※本不具合は表示上のみの不具合です。</div><br>【3/2 14:35追記】<br><div class=\"postscript-01\">・1st Anniversary記念ショップ内にて特定の手順を行った際、[フレンドPt]のタブが選択できない場合がある。<br>※本不具合が発生した際は、一度ホームに戻り、再度1st Anniversary記念ショップに移動することで解消されます。<br>・ショップの「限定セール」がオープンしている状態で特定の手順を行った際、[蹄鉄交換]、[結晶片交換]で「限定セール」でないにもかかわらず[今すぐ閉じる]が表示される場合がある。<br>※[蹄鉄交換]、[結晶片交換]で表示されている[今すぐ閉じる]を選択すると、「限定セール」は閉じられます。<br>・特定の手順でミッション画面の「挑戦する」ボタンからジュークボックスに移動し、「ウマいね！」を行うと「エラーコード：102」が表示される。<br>※本現象は、アプリを再起動して再度楽曲リクエストを行っていただくことで、解消されます。<br>・「TP回復」のアイテム一覧画面において、画面中央部をスワイプしてもスクロールすることができない。<br>※画面右部に配置されているスクロールバーを押さえて上下に動かすことによってスクロールすることができます。<br>・練習のレース結果画面において、着順やたづなからのアドバイスなどの一部表記が意図した表記と異なっている。<br>・「We are DREAMERS!!」のライブにて、ライブ一時停止中に画面右下のボタンから「非表示」設定にしても歌詞のルビ部分のみ非表示にならない。</div><br>【2/22 20:55追記】<br><div class=\"postscript-01\">・特定の操作を行うと、トレーナーノートの一部ボイスを解放できない場合がある。</div><br>【2/16 19:45追記】<br><div class=\"postscript-01\">・サークルメンバーを除名した際に、受け取れるプレゼントがないにもかかわらず、ホーム画面のプレゼントアイコンに未受け取り件数が表示される場合がある。</div><br>【2/16 19:05追記】<br><div class=\"postscript-01\">・ファインモーションの育成において、シニア級の有馬記念に出走した際に、育成イベント「有馬記念にむけて」が発生しない場合がある。</div><br>【2/14 16:45追記】<br><div class=\"postscript-01\">・一部ウマ娘の「育成ウマ娘詳細」育成イベントにて、特定の手順を行った場合、同一イベントが複数表示される場合がある。<br>※本不具合は表示上のみの不具合です。</div><div class=\"postscript-01\">・イベント「レーシングカーニバル」にて、特定の操作を行うとチャレンジレース発生演出の表示が崩れる。</div><div class=\"postscript-01\">・「アオハル杯～輝け、チームの絆～」にて、トレーニング失敗時にアオハル特訓のアイコンが表示されているウマ娘の絆ゲージが上昇する演出が表示される。<br>※本不具合は表示上のみの不具合です。</div><br>【2/8 16:40追記】<br><div class=\"postscript-01\">・エイシンフラッシュの育成ウマ娘イベント「Erinnerung an den Sieg」の一部において、衣装が意図した表示と異なっている。</div><br>【2/3 16:20追記】<br><div class=\"postscript-01\">・イベント「トレーナー技能試験」に挑戦中の「アオハル杯～輝け、チームの絆～」の育成にて、特定の手順を行った場合、チーム編成画面から[戻る]を選択すると、ショップ画面に移動する場合がある。</div><div class=\"postscript-01\">・イベント「トレーナー技能試験」にて、初回に挑戦した試験で育成中、画面右上にイベントの表示が出ない。<br>※本現象は、アプリを再起動することで解消されます。</div><br>【2/1 12:30追記】<br><div class=\"postscript-01\">・メジロドーベルの育成ウマ娘イベント「香りの魔術師」において、上の選択肢を選んだ場合に下の選択肢のストーリーが続けて再生される場合がある。本不具合が発生した場合にメジロドーベルの表示が崩れる。<br>※本不具合は表示上のみの不具合で、付与されるパラメータは選んだ選択肢に応じて正常に付与されます。</div><br>【2/1 12:30追記】<br><div class=\"postscript-01\">・ストーリーイベント開始時と、ストーリーイベントのトップ画面左上から確認できるイベント説明において、イベントミッションの記載に一部誤りがある。</div><br>【1/28 12:58追記】<br><div class=\"postscript-01\">・サクラチヨノオーの育成ウマ娘イベント「休息はバッチリ！」において、衣装が意図した表示と異なっている。</div><div class=\"postscript-01\">・イベント「瑞花繚乱！新春かるた合戦」にて、特定の操作を行うと累計イベントPtが表示されなくなる。<br>※本不具合が発生した場合、イベントのトップ画面に入り直していただくことでイベントPtを確認することができます。</div><br>【1/21 12:47追記】<br><div class=\"postscript-01\">・サクラチヨノオーの目標レース「天皇賞（秋）」（シニア級）において、レースに出走しているウマ娘が意図した内容と異なっている。</div><br>【1/20 15:45追記】<br><div class=\"postscript-01\">・一部の二つ名において、条件を達成せずとも獲得できてしまう場合がある。<br>・イナリワンのサポートカードイベント「成長のヒント」において、夏合宿期間中に発生した場合の背景が意図した表示と異なっている。<br>・ライブシアターのメンバー選択画面にて、「指定なし」を選択した際に同一のウマ娘が重複して設定される場合がある。<br>※既に同一のウマ娘が重複して設定されている場合は、再度「指定なし」を選択することで、以降同一のウマ娘が設定されなくなります。<br>・「アオハル杯～輝け、チームの絆～」においてアオハル杯のレースに登場するメジロアルダンの動きが想定と異なっている。<br>※本不具合は表示上のみの不具合です。レースにおけるパラメータに影響はありません。</div><br>【1/19 12:25追記】<br><div class=\"postscript-01\">・ホーム画面の[ミッション]ボタンに、未受け取りのミッション報酬がないにも関わらずバッジが表示される場合がある。</div><div class=\"postscript-01\">・練習において、特定の手順でレースを開始するとエラーが発生し、練習が進行不能になる場合がある。</div><div class=\"postscript-01\">・ウマ娘詳細の継承履歴に、同じ継承履歴が重複して表示される場合がある。</div><div class=\"postscript-01\">・イベント「レーシングカーニバル」にて、特定の操作を行うと一部の効果音が再生され続けてしまう。</div><div class=\"postscript-01\">・友人タイプのサポートカードについて、育成中のお出かけイベント回数が誤って表示されている場合がある。<br>※本不具合は表示上のみの不具合です。</div><br>【1/11 17:13追記】<br><div class=\"postscript-01\">・ウマ娘イベント「あんし～ん笹針師、出☆没」の特定の選択肢にて、意図していない「成功」演出が表示される場合がある。<br>※本不具合は表示上のみの不具合です。</div><br>【12/31 12:40追記】<br><div class=\"postscript-01\">・メジロドーベルのウマ娘ストーリー第2話で、レースシーンの表示が崩れる場合がある。</div><div class=\"postscript-01\">・メインストーリー第5章 第3Rのレース限定スキル「鮮明になる畏怖」にて、説明文の表記が意図した表記と異なっている。<br>※スキルの効果には影響ありません。</div><br>【12/23 16:05追記】<br><div class=\"postscript-01\">・タマモクロスの育成ウマ娘イベント「先駆けの稲妻」において、トウカイテイオーの衣装が意図した表示と異なっている。</div><br>【12/23 16:05追記】<br><div class=\"postscript-01\">・イベント「レジェンドレース」にて、有馬記念の表記が意図した表記と異なっている。</div><br>【12/22 15:45追記】<br><div class=\"postscript-01\">・ファインモーションのウマ娘ストーリー第2話にて、ファインモーションが走っている場面で表示が崩れる場合がある。</div><br>【12/13 12:37追記】<br><div class=\"postscript-01\">・「アオハル杯～輝け、チームの絆～」にて、アオハル杯開催時に編成しているメンバーが10人未満の状態で[編成確定]を選択すると「エラーコード：205」が表示される。</div><div class=\"postscript-01\">・「アオハル杯～輝け、チームの絆～」にて、チュートリアルの選択肢[もう大丈夫です]以外を選び続けると、ログを開く動作が重くなる場合がある。</div><br>【12/08 12:05追記】<br><div class=\"postscript-01\">・[エレガンス・ライン]メジロマックイーンの固有スキル「貴顕の使命を果たすべく」の説明文を一部修正しました。<br><br>■修正前<br>最終コーナーで前の方にいると抜かさせない覚悟を決めて速度が上がる<br><br>■修正後<br>最終コーナーで前の方にいると抜かせない覚悟を決めて速度が上がる<br>※スキルの効果には影響ありません</div><br><br>■修正見送りの不具合<br>下記の現象において、仕様として修正を見送りといたします。<br>【10/27 12:25追記】<br><div class=\"postscript-01\">・ギャラリーにて、夏合宿中に発生した一部の育成イベントが解放されない。</div><div class=\"postscript-01\">・特定の環境にて、育成開始時のタイトルロゴおよび、チュートリアル中のレースロゴが表示されない場合がある。</div><br><br>本不具合は、今後のアップデートで修正を予定しております。<br>修正完了まで、今しばらくお待ちくださいますよう、お願いいたします。<br><br>ご利用のお客様に、ご迷惑をおかけしておりますことを、お詫び申し上げます。"
soup = BeautifulSoup(message, "html.parser")

for element in soup:
    print(element.name, element.text)


quit()

import mal_tools as mal
import database_tools as db


conn, cursor = db.get_connection()

cursor.execute("""select w.id, i.character_id from images i
JOIN waifus w on w.images_id = i.id
where normal_url is null;
""")
rows = cursor.fetchall()
for row in rows:
    waifu_id = row[0]
    char_id = row[1]


conn.commit()
conn.close()


db.removeUselessWaifus()

mal.downloadInsertShowCharacters("")

mal.downloadInsertShowCharacters("https://myanimelist.net/manga/7519/Kami_nomi_zo_Shiru_Sekai/")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/123450/Saikin_Yatotta_Maid_ga_Ayashii")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/138079/Genshin_Comic_Anthology")

mal.downloadInsertShowCharacters("https://myanimelist.net/anime/33573/BanG_Dream")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/48753/Jahy-sama_wa_Kujikenai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/48556/Takt_Op_Destiny")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/22147/Amagi_Brilliant_Park")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10721/Mawaru_Penguindrum")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/16732/Kiniro_Mosaic")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10495/Yuru_Yuri")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/36259/Pingu_in_the_City")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/37430/Tensei_shitara_Slime_Datta_Ken")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39551/Tensei_shitara_Slime_Datta_Ken_2nd_Season")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10165/Nichijou")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/3446/Maker_Hikoushiki_Hatsune_Mix")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/43299/Wonder_Egg_Priority")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/33489/Little_Witch_Academia_TV")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/6594/Katanagatari")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/34053/Umineko_no_Naku_Koro_ni_Chiru_-_Episode_8__Twilight_of_the_Golden_Witch")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/16144/Umineko_no_Naku_Koro_ni_-_Episode_4__Alliance_of_the_Golden_Witch")
mal.downloadInsertShowCharacters("http://www.myanimelist.net/anime/33674/No_Game_No_Life__Zero")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/13601/Psycho-Pass")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/2966/Ookami_to_Koushinryou")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/5341/Ookami_to_Koushinryou_II")
#mal.downloadInsertShowCharacters("https://myanimelist.net/anime/33255/Saiki_Kusuo_no_%CE%A8-nan")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/41457/86")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/48569/86_Part_2")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/25777/Shingeki_no_Kyojin_Season_2")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40591/Kaguya-sama_wa_Kokurasetai__Tensai-tachi_no_Renai_Zunousen")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31716/Rewrite")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/30307/Monster_Musume_no_Iru_Nichijou")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/36633/Date_A_Live_III")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/41006/Higurashi_no_Naku_Koro_ni_Gou")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/14131/Girls___Panzer")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39247/Kobayashi-san_Chi_no_Maid_Dragon_S")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10087/Fate_Zero")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/33263/Kubikiri_Cycle__Aoiro_Savant_to_Zaregototsukai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35760/Shingeki_no_Kyojin_Season_3")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/14813/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/23847/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru_Zoku")
# mal.downloadInsertShowCharacters("https://myanimelist.net/manga/121523/Fire_Emblem_Heroes__Eiyuu-tachi_no_Nichijou")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10012/Carnival_Phantasm")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/41307/Tokyo_7th_Sisters__Bokura_wa_Aozora_ni_Naru")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35503/Shoujo%E2%98%86Kageki_Revue_Starlight")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40571/Majo_no_Tabitabi")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/38005/Strike_Witches__Road_to_Berlin")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32866/Brave_Witches")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35983/Harukana_Receive")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/44274/Puraore_Pride_of_Orange")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/9260/Kizumonogatari_I__Tekketsu-hen")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31757/Kizumonogatari_II__Nekketsu-hen")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31758/Kizumonogatari_III__Reiketsu-hen")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/5081/Bakemonogatari?q=bakemonogatari&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/11597/Nisemonogatari?q=nisemonog&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/15689/Nekomonogatari__Kuro?q=monogatari&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/17074/Monogatari_Series__Second_Season?q=monog&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/28025/Tsukimonogatari?q=tsuki&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/21855/Hanamonogatari?q=hana&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31181/Owarimonogatari?q=owari&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35247/Owarimonogatari_2nd_Season?q=owari&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/36999/Zoku_Owarimonogatari?q=zoku%20owari&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/91941/Made_in_Abyss?q=made%20in%20abyss&cat=manga")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood?q=full%20metal%20alchemist&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/205/Samurai_Champloo?q=samurai%20cham&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/18679/Kill_la_Kill?q=kill&cat=anime")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/108495/NieR_Automata?q=nier&cat=manga")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/38573/Tsuujou_Kougeki_ga_Zentai_Kougeki_de_Ni-kai_Kougeki_no_Okaasan_wa_Suki_Desu_ka")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10012/Carnival_Phantasm")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/44042/Holo_no_Graffiti")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/5376/Touhou_Gumonshiki__Memorizable_Gensokyo")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/175/Touhou_Sangetsusei__Eastern_and_Little_Nature_Deity")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/11929/Touhou_Sangetsusei__Strange_and_Bright_Nature_Deity")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/14439/Touhou_Sangetsusei__Oriental_Sacred_Place")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/96369/Touhou_Sangetsusei__Visionary_Fairies_in_Shrine")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/3014/Touhou_Bougetsushou__Silent_Sinner_in_Blue")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/5373/Touhou_Bougetsushou__Cage_in_Lunatic_Runagate")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/9429/Touhou_Bougetsushou__Tsuki_no_Inaba_to_Chijou_no_Inaba")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/21054/Touhou_Ibara_Kasen__Wild_and_Horned_Hermit")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/44523/Touhou_Suzunaan__Forbidden_Scrollery")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/123038/Touhou_Suichouka__Lotus_Eater-tachi_no_Suisei")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/122572/Touhou_Chireikiden__Hansoku_Tantei_Satori")
mal.downloadInsertShowCharacters("https://myanimelist.net/manga/14466/Touhou_Kourindou__Curiosities_of_Lotus_Asia")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/38853/Ex-Arm")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/46095/Vivy__Fluorite_Eyes_Song")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35839/Sora_yori_mo_Tooi_Basho")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/849/Suzumiya_Haruhi_no_Yuuutsu")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40550/Assault_Lily__Bouquet")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/11867/Cipher")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35849/Darling_in_the_FranXX")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/28221/Etotama")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/20541/Mikakunin_de_Shinkoukei")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31953/New_Game")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/66/Azumanga_Daioh")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/934/Higurashi_no_Naku_Koro_ni")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/9756/Mahou_Shoujo_Madoka%E2%98%85Magica")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39535/Mushoku_Tensei__Isekai_Ittara_Honki_Dasu")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/5042/Kiss_x_Sis")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/18041/Rozen_Maiden_2013")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/30/Neon_Genesis_Evangelion")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/33352/Violet_Evergarden")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/43439/Shadows_House")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/3455/To_LOVE-Ru")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/4224/Toradora")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/1195/Zero_no_Tsukaima")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31646/3-gatsu_no_Lion")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/42653/Aikatsu_Planet")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/44275/Selection_Project")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40842/Idoly_Pride")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40148/22_7")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39071/Machikado_Mazoku")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/623/Shichinin_no_Nana")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32937/Kono_Subarashii_Sekai_ni_Shukufuku_wo_2")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/27441/Show_By_Rock")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32038/Show_By_Rock_")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/38009/Re_Stage_Dream_Days%E2%99%AA")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/11785/Haiyore_Nyaruko-san")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/15699/Haiyore_Nyaruko-san_W")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40763/Show_By_Rock_Mashumairesh")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/41520/Show_by_Rock_Stars")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39681/D4DJ__First_Mix")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39292/Princess_Connect_Re_Dive")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/13659/Ore_no_Imouto_ga_Konnani_Kawaii_Wake_ga_Nai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/34798/Yuru_Camp%E2%96%B3")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/38474/Yuru_Camp%E2%96%B3_Season_2")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32268/Koyomimonogatari")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/9253/Steins_Gate")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/19815/No_Game_No_Life")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/383/Galaxy_Angel")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/38992/Rikei_ga_Koi_ni_Ochita_no_de_Shoumei_shitemita")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/1887/Lucky%E2%98%86Star")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/2167/Clannad")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/4181/Clannad__After_Story")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/14741/Chuunibyou_demo_Koi_ga_Shitai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/18671/Chuunibyou_demo_Koi_ga_Shitai_Ren")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/11751/Senki_Zesshou_Symphogear")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/15793/Senki_Zesshou_Symphogear_G")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/21573/Senki_Zesshou_Symphogear_GX")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32836/Senki_Zesshou_Symphogear_AXZ")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32843/Senki_Zesshou_Symphogear_XV")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/21273/Gochuumon_wa_Usagi_Desu_ka")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/29787/Gochuumon_wa_Usagi_Desu_ka")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/35249/Uma_Musume__Pretty_Derby_TV")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/37916/Uma_Musume__Pretty_Derby_-_BNW_no_Chikai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/42941/Uma_Musume__Pretty_Derby_TV_Season_2")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/16157/Choujigen_Game_Neptune_The_Animation")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/15051/Love_Live_School_Idol_Project")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32526/Love_Live_Sunshine")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/40879/Love_Live_Nijigasaki_Gakuen_School_Idol_Doukoukai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/41169/Love_Live_Superstar")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/30547/Touhou_Niji_Sousaku_Doujin_Anime__Musou_Kakyou_Special")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/9874/Touhou_Niji_Sousaku_Doujin_Anime__Musou_Kakyou")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/36686/Hifuu_Katsudou_Kiroku__The_Sealed_Esoteric_History")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/32901/Eromanga-sensei")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/8769/Ore_no_Imouto_ga_Konnani_Kawaii_Wake_ga_Nai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/6547/Angel_Beats")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/28999/Charlotte")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/16706/Kami_nomi_zo_Shiru_Sekai__Megami-hen")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/21085/Witch_Craft_Works")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/13759/Sakura-sou_no_Pet_na_Kanojo")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/27775/Plastic_Memories")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/8525/Kami_nomi_zo_Shiru_Sekai")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/10080/Kami_nomi_zo_Shiru_Sekai_II")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/15117/Kami_nomi_zo_Shiru_Sekai__Tenri-hen")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/31240/Re_Zero_kara_Hajimeru_Isekai_Seikatsu")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/42203/Re_Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season_Part_2")
mal.downloadInsertShowCharacters("https://myanimelist.net/anime/39587/Re_Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season")

db.createDatabase()

db.insertCharacter(mal.downloadCharacter(13468))
db.insertCharacter(mal.downloadCharacter(14015))
db.insertCharacter(mal.downloadCharacter(18866))
db.insertCharacter(mal.downloadCharacter(22306))
db.insertCharacter(mal.downloadCharacter(15636))
db.insertCharacter(mal.downloadCharacter(15449))
db.insertCharacter(mal.downloadCharacter(22322))
db.insertCharacter(mal.downloadCharacter(26275))
db.insertCharacter(mal.downloadCharacter(61371))
db.insertCharacter(mal.downloadCharacter(64167))
db.insertCharacter(mal.downloadCharacter(64173))
db.insertCharacter(mal.downloadCharacter(64169))
db.insertCharacter(mal.downloadCharacter(64165))
db.insertCharacter(mal.downloadCharacter(22037))
db.insertCharacter(mal.downloadCharacter(109213), alt_name="trash")
db.insertCharacter(mal.downloadCharacter(8128))
db.insertCharacter(mal.downloadCharacter(25170))
db.insertCharacter(mal.downloadCharacter(16192))
db.insertCharacter(mal.downloadCharacter(25171))
db.insertCharacter(mal.downloadCharacter(16193))
db.insertCharacter(mal.downloadCharacter(25169))
db.insertCharacter(mal.downloadCharacter(16194))
db.insertCharacter(mal.downloadCharacter(38940), alt_name="nae nae")
db.insertCharacter(mal.downloadCharacter(110137))
