import mal_tools as mal
import database as db

quit()

db.createDatabase()

db.insertCharacter(mal.downloadCharacter(13468))
db.insertCharacter(mal.downloadCharacter(14015))
db.insertCharacter(mal.downloadCharacter(18866))
db.insertCharacter(mal.downloadCharacter(22306))
db.insertCharacter(mal.downloadCharacter(15636))
db.insertCharacter(mal.downloadCharacter(15449))
db.insertCharacter(mal.downloadCharacter(22322))
db.insertCharacter(mal.downloadCharacter(26275))
db.insertCharacter(mal.downloadCharacter(61371))
db.insertCharacter(mal.downloadCharacter(64167))
db.insertCharacter(mal.downloadCharacter(64173))
db.insertCharacter(mal.downloadCharacter(64169))
db.insertCharacter(mal.downloadCharacter(64165))
db.insertCharacter(mal.downloadCharacter(22037))
db.insertCharacter(mal.downloadCharacter(109213), "trash")
db.insertCharacter(mal.downloadCharacter(8128))
db.insertCharacter(mal.downloadCharacter(25170))
db.insertCharacter(mal.downloadCharacter(16192))
db.insertCharacter(mal.downloadCharacter(25171))
db.insertCharacter(mal.downloadCharacter(16193))
db.insertCharacter(mal.downloadCharacter(25169))
db.insertCharacter(mal.downloadCharacter(16194))
db.insertCharacter(mal.downloadCharacter(38940), "nae nae")
db.insertCharacter(mal.downloadCharacter(110137))
